### PR TITLE
Add locale data for date, datetime and pickers

### PR DESCRIPTION
**Pull request by Nerian**
Hi,

This adds locale support for Date, Datetime and Time pickers.

For it to work it needs locale data from the MomentJS. EffectiveBoostrap doesn't ship moment with the locale. What I do is to include `gem 'momentjs-rails', '~> 2.9', github: 'derekprior/momentjs-rails'` in my Gemfile and then:

```
//= require moment/es.js
//= require moment/nl.js
```

But I think it would be better to either include the locale data in EffectiveBootstrap or simply add momentjs-rails as a dependency of effective_bootstrap. 

Thoughts?

### CODE REVIEW

**Comment by matt-riemer** [comment]
This seems to just work for "en" locale :)

 I do see javascript errors for other locales, but I'm okay with that.  If you keep doing the moment-js-rails override that can work just fine!

**Comment by matt-riemer** [comment]
Released as effective_bootstrap 0.4.8

**Comment by Nerian** [comment]
Cool, thanks!

Yeah, off the shelves it will only works for the 'en' locale unless you include the locale data for Moment.js

Like this data:
https://github.com/derekprior/momentjs-rails/tree/master/vendor/assets/javascripts/moment

We could copy those into effective_bootstrap and ship it – like what we do in the PR in  EffectiveDatatable – that way it is a complete package. I can make the PR if you agree.

**Comment by Nerian** [comment]
I had some minutes before dinner so I just went ahead and made the PR 😄 

https://github.com/code-and-effect/effective_bootstrap/pull/9

**Pull request merged**
